# Generated by Django 5.0.6 on 2024-06-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
