# Generated by Django 5.0.6 on 2024-06-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
